Create container-runtime-survey2021.md
supercontainers/containers-wg pull request #36
Opened 2021-08-23 14:07 UTC by kniec

2021-08-23 14:15 UTC, vsoch reviewed
I love this idea! Ping me if you want any help? It would be good to have some sort of branding so we can do this survey regularly and it becomes a well known (hopefully fun and quick) thing! Maybe we can have a repo for just the survey results, and one where we can create plots for each year? (I can help with this!)

2021-08-23 14:15 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +A survey to get some data on container runtime would be nice. Not only which once are used, but also what images are used (OCI) and how hardned the feelings are (use of multiple runtimes).
```suggestion
A survey to get some data on container runtime would be nice. Not only which ones are used, but also what images are used (OCI) and how hardened the feelings are (use of multiple runtimes).
```

2021-08-23 14:15 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +| R2 | How many HPC container runtimes are you using in your daily live for the last 6 month? | single choice | 0,1,2,3,4,5 |
daily life == personal development and work development?
```suggestion
| R2 | How many HPC container runtimes are you using in your daily life for the last 6 month? | single choice | 0,1,2,3,4,5 |
```

2021-08-23 14:15 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +| R3 | Which HPC container runtimes are you using for your daily workloads? | multiple-choice | Charliecloud, Shifter, Singularity, Sarus, Podman |
How is this one different from the previous, is the difference just in the last 6 months or not? Also, we probably want to throw in Docker, it's fair game for using in personal development (I use it every day).

2021-08-23 14:15 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +| R3 | Which HPC container runtimes are you using for your daily workloads? | multiple-choice | Charliecloud, Shifter, Singularity, Sarus, Podman |
And should we have some ability to specify "Other" with a fill in the blank for it? E.g., udocker and some lesser known ones.

2021-08-23 14:15 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +| R4 | Which HPC container runtimes are on your radar but not yet used? | multiple-choice | Charliecloud, Shifter, Singularity, Sarus, Podman |
And other (fill in the blank)

2021-08-23 14:15 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +| I1 | What description do you use regularily to build your images? | multi | Dockerfile, SIF recipe, ... |
We might want to account for recipe / other makers like hpc-container-maker, repo2docker, although those are primarily Dockerfile, it could be that the reader doesn't know that since it happens under the hood. Or just put another "Other" and fill in the blank here!

2021-08-23 14:19 UTC, kniec commented on _ideas/container-runtime-survey2021.md
> +| R3 | Which HPC container runtimes are you using for your daily workloads? | multiple-choice | Charliecloud, Shifter, Singularity, Sarus, Podman |
I had Docker in before; I thought it is going to be hard to differentiate between a real HPC workload or an HPC system if we allow Docker to join.
On R1,R2,R3: Yeah, maybe R1&R2 with multiple choice plus other

2021-08-23 14:21 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +| R3 | Which HPC container runtimes are you using for your daily workloads? | multiple-choice | Charliecloud, Shifter, Singularity, Sarus, Podman |
Ah, that makes sense. Maybe in the description we can mention that we are intentionally not asking about Docker (so if they are looking for it and don't see it they don't exit the survey, which is something I've done before for other things, heh).

2021-08-23 14:31 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +| R1.5 | Which HPC container runtimes are supported on the system(s) and not listed in R1? | text | |
Just to clarify - these X.5 questions are for the “other” choice? What does the 5 indicate?

2021-08-23 14:31 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +| I2 | Do you use higher-level abstractions on-top of the methods in I1? | multi | hpc-container-maker, repo2docker, spack, other |
Oh yeah good call on spack!

2021-08-23 14:37 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +| R1.5 | Which HPC container runtimes are supported on the system(s) and not listed in R1? | text | |
I see the comment - thanks!

2021-08-23 14:39 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +| I4 | What container repositories are you pushing builds to? | multi | dockerhub, gcr, ecr, quay, github |
Does Microsoft have one? https://azure.microsoft.com/en-us/services/container-registry/
```suggestion
| I4 | What container repositories are you pushing builds to? | multi | dockerhub, gcr, ecr, quay, github, azure |
```

2021-08-23 14:41 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +Without making the survey to long, we could also ask about.
```suggestion
Without making the survey too long, we could also ask the following questions.
```

2021-08-23 14:41 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +2. Do you use CI/CD?
```suggestion
2. Do you use CI/CD for automated build and deploy?
```
We might want to distinguish using it for test, build and deploy, or both.

2021-08-23 14:41 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +1. do you deal with different target architectures in your build process?
Do we care which architectures?
Maybe something about “I need my container to work with” … GPU, MPI, etc.

2021-08-23 15:00 UTC, kniec commented on _ideas/container-runtime-survey2021.md
> +1. do you deal with different target architectures in your build process?
> Do you need your container to be tailored for a specific system (MPI, GPU)?
But I am not sure if we want to make the survey go down this complexity route which we do not yet have a common understanding for...

2021-08-23 15:00 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +1. do you deal with different target architectures in your build process?
Yeah that’s fair!

2021-08-23 16:25 UTC, ajyounge commented on _ideas/container-runtime-survey2021.md
> +1. do you deal with different target architectures in your build process?
I do care about alternative architectures. However I would like to suggest question should be more general to include GPUs and/or accelerators, rather than just CPU ISAs. 

"In your container build process, do you target more than 1 type of hardware configuration (different CPUs, GPUs, accelerators, ...)?"

2021-08-23 16:28 UTC, ajyounge commented
I'm curious about a few things and want to make sure this is targeted appropriately. 

1. What's the ideal/best outcome of this survey? 
2. What could inform us on that we may not know today?  
3. Who is the target audience to complete the survey?
4. How will it be distributed?

I'm generally supportive of taking community temperatures with surveys, but I also want to make sure they have specific use and value.

2021-08-23 16:32 UTC, vsoch commented
I can give a shot at (what I think) are answers:

>  What's the ideal/best outcome of this survey?

This is primarily about understanding, not just in the present moment, but change over time. For example, we'd want to be able to see that container technology X isn't used as much today, but maybe becomes the prominent technology over time, and make sure this understanding is known to the larger community, and places like OCI if someone asks.

> What could inform us on that we may not know today?

We might be surprised to learn that some technology is used more places than we think, or vice versa. 

> Who is the target audience to complete the survey?

Anyone with access to an HPC cluster, and that include admins and users.

> How will it be distributed?

We will need to use all venues possible - so slacks, email lists, and Twitter.

2021-08-23 16:36 UTC, kniec commented
+1 on what @vsoch wrote. IMHO a lightweight survey we can do every once and again. 

My main reason is to find out about use of container runtimes in general. And how bound folks are to one particular one.
I hope to see folks don't be to stressed about which runtime they use - but that might be wrong.

2021-08-23 16:50 UTC, vsoch commented
What should we call it? I would like if it's branded to be created from the Containers Working Group, so it's clearly agnostic to specific companies / vendors, clearly has a goal of understanding (as opposed to a company trying to measure customers) and it's felt that it's owned/driven by the same community. Maybe just something like:

 - Containers Working Group Annual Survey
 - Supercontainers Working Group Annual Survey

and then each of the above, but with "for HPC" added if we want to scope it to that. @kniec I can help with creating it if you like, I actually think a Google form is sound so we can link it to a Google sheet for easy data export. My suggestions for next steps:

1. decide on a title / branding
2. create it in the form, get more feedback from the containers-wg channel
3. decide on a release date (and how long open)
4. I can then create a site around the exported data, the idea that it will be ready to just dump data from a new year to render on the site.
5. Then we share with the community woo!

2021-08-24 07:32 UTC, kniec commented
### 1. Title
I changed the name to 
> Containers Working Group for HPC Survey

Vendor agnostic for sure. Maybe @cnewburn has some ideas as well?

I also reckon `Annual` is rather sparse. At least before ISC and SC would be cool. Maybe `quarterly`? 

### 2. Form
To keep the bar to take the survey low I strongly suggest we make it so that you do not need to allow cookies or even log in to google to take it. If that is possible with Google Form, fine...

### 3. Release date
ASAP :) 

### 4. Site
I guess a github page is enough, but feel free to take it away. :)

2021-08-24 16:36 UTC, vsoch commented
> I also reckon Annual is rather sparse. At least before ISC and SC would be cool. Maybe quarterly?

Quarterly feels to often to me - asking folks about what they use once a year I think is sufficient, but curious to hear other's opinions.

And for forms I'm pretty sure you can just not collect emails / receipts and it should not track anyone:

![image](https://user-images.githubusercontent.com/814322/130655103-ae3a2f50-b8aa-4e1a-b31d-db79c5ba71c0.png)

At least based on those things :) We probably want to open/close the survey however to ensure that no new results come in. I guess the risk of being anonymous is if someone decides to spam it, but we can start with the assumption that people are good and won't do that!

2021-08-29 04:22 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +| A2.5 | Which functionis not listed in A2? | text | |
```suggestion
| A2.5 | Which function is not listed in A2? | text | |
```

2021-09-02 17:53 UTC, ArangoGutierrez commented
> ### 1. Title
> 
> I changed the name to
> 
> > Containers Working Group for HPC Survey
> 
> Vendor agnostic for sure. Maybe @cnewburn has some ideas as well?
> 
> I also reckon `Annual` is rather sparse. At least before ISC and SC would be cool. Maybe `quarterly`?
> ### 2. Form
> 
> To keep the bar to take the survey low I strongly suggest we make it so that you do not need to allow cookies or even log in to google to take it. If that is possible with Google Form, fine...
> ### 3. Release date
> 
> ASAP :)
> ### 4. Site
> 
> I guess a github page is enough, but feel free to take it away. :)

`anual` is more than ok, trust me, from running a container tutorial for years in a row, HPC moves at a diff speed than Cloud. if you try something more than `anual` you will loose people interest

2021-09-02 18:03 UTC, vsoch commented
Notes from the meeting:

 - "What's 20% of your problem that's taking 80% of your time?) Or in other words, giving people an open ended box to ask about what are their challenges and obstacles, and then that gives us an ability to possibly follow up with them to get more detail.
 - Forward thinking - would you be interested in X? What do you want to do but don't have time for? To get a sense of any forward thinking that is happening

@kniec we missed you! But I think we had good discussions and folks know about the PR here. Let me know your thoughts on the above and what that might look like (and I can make suggestions for that too).

2021-09-03 03:08 UTC, vsoch reviewed
Just gave another review after the call today! I'm worried that we are explicitly leaving out Docker because it's not considered an "HPC" container. But I know there are the rare centers out that that do give access to it, whether on a cluster or a small private space. I kind of feel like we should be including it in all of these questions and let the data speak for itself instead of forcing people / not allowing them to include it.

2021-09-03 03:08 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +| A4 | How do you rate your experience with **HPC containers**? | single | beginner, intermediate, expert |
```suggestion
| A4 | How do you rate your experience with **HPC containers**? | single | no experience, beginner, intermediate, expert |
```

2021-09-03 03:08 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +| A4 | How do you rate your experience with **HPC containers**? | single | beginner, intermediate, expert |
Added this because I do think there is a difference between "I have never touched a container technology" and "I am a beginning with container technologies" and we would want to be able to tell these apart.

2021-09-03 03:08 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +This section is focused to ask about HPC workloads running on HPC container runtimes. Some might use docker to run a single-node container on their workstation - we consider that out of scope because
```suggestion
This section is focused to ask about HPC workloads running on HPC container runtimes. While some might use docker to run a single-node container on their workstation, we do not consider it in this set because it is not traditionally used in HPC environment.
```

2021-09-03 03:08 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +This section is focused to ask about HPC workloads running on HPC container runtimes. Some might use docker to run a single-node container on their workstation - we consider that out of scope because
I agree that Docker is more "service" and the others possibly not, but I don't think the average user will make this distinction. If you look at the R community, for example, they run many pipelines with Docker and wouldn't label those runs as "services" and this question wording might be confusing.

2021-09-03 03:08 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +| I3 | Once build, do you push the image to a central repository? | single | yes / no |
```suggestion
| I3 | Once build, do you push the image to a central registry? | single | yes / no |
```

2021-09-03 03:08 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +| I4 | What container repositories are you pushing builds to? | multi | dockerhub, gcr, ecr, quay, github, azure |
```suggestion
| I4 | What container registries are you pushing builds to? | multi | Docker Hub, Google Container Registry (gcr), Elastic Container Registry (ecr), Quay.io, GitHub Packages (ghcr,io), Azure |
```

2021-09-03 03:08 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +2. Do you use CI/CD for automated build and deploy?
```suggestion
2. Do you use CI/CD for automated build and deploy?
3. What are you biggest challenges or pain points when using containers, or reasons that you don't use them (fill in the blank)
4. What do containers not do that you wish they could? What would be an ideal future?
```

2021-09-03 21:00 UTC, ArangoGutierrez commented
Just a nit, could we squash all the commits and give them a proper description.

2021-09-03 21:33 UTC, ArangoGutierrez requested changes

2021-09-03 21:33 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +
This text sounds ok for the actual survey, but here @kniec is trying to describe the idea/project first, IMO, right?

2021-09-03 21:33 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +| A1 | What is your primary environment? | single | National Lab, academia, commercial, other |
`s/National Lab/Govberment lab/` National lab is very US central, other places is just call gov lab

2021-09-03 21:33 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +| A2 | What is your function? | single | Scientist, Admin, RSE, other |
Agree with V
I would add the very basic `software engineer` (bc that's my job title)

2021-09-03 21:33 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +| A2.5 | Which functionis not listed in A2? | text | |
++

2021-09-03 21:33 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +| A3 | How do you rate your experience with **non-HPC containers**? | single | beginner, intermediate, expert |
Very confusing question, you mean, web services and related topics?

2021-09-03 21:33 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +This section is focused to ask about HPC workloads running on HPC container runtimes. Some might use docker to run a single-node container on their workstation - we consider that out of scope because
the docker word could be replaced for generic `container tech` IMO

2021-09-03 21:33 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +| R4 | Do you aware of the OCI runtime spec? | single choice | yes / no |
```suggestion
| R4 | Are you aware of the OCI runtime spec? | single choice | yes / no |
```

2021-09-03 21:33 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +| R4 | Do you aware of the OCI runtime spec? | single choice | yes / no |
that or `Do you acknowledge` , but as it is is not well redacted

2021-09-03 21:33 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +The image section aims to get an overview of how folks are dealing with images
```suggestion
The image section aims to get an overview of how users are interacting with container images (building, sharing, Storing)
```

2021-09-03 21:33 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +| I1 | What is the method you are using to build a container image from scratch? | multi | Dockerfile, SIF recipe, other |
```suggestion
| I1 | What is the method you are using to build a container image? | multi | Dockerfile, SIF recipe, From scratch, other |
```

2021-09-03 21:33 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +| I1 | What is the method you are using to build a container image from scratch? | multi | Dockerfile, SIF recipe, other |
From scratch is an actual valid way supported by Buildah

2021-09-03 21:33 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +| I1 | What is the method you are using to build a container image from scratch? | multi | Dockerfile, SIF recipe, other |
now that I think it better this question is wrong, you `build` a container with a container runtime tool, a Dockerfile or SIF def, is a way to `DEFINE` a  container image. we should have 2 questions
1 preferred def file 
2 way of building the def file

2021-09-03 21:33 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +| I4 | What container repositories are you pushing builds to? | multi | dockerhub, gcr, ecr, quay, github, azure |
I would re-write I3 and I4, some labs use NFS systems to store the container images, so they don't `PUSH` , simple move.
so I3 should be, `How do you store your container images after build`
I4 Which container registry is used at your institution to store and share images

that way answers will be more meaning full to reviewers

2021-09-03 21:33 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +1. do you deal with different target architectures in your build process?
I would call it `build process` , the question should be
> Do you have to build your container image for different CPU architectures?
> DO you care about available accelerators(GPU, FPGA, specialized network hardware) when building your container image?

2021-09-03 21:33 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +2. Do you use CI/CD for automated build and deploy?
I like the intend but when reviewing the results I would like to have more insight
2. Does you institution has a CI implemented for container image builds?
3. Does your institution allows you to pull from external registries without going through the institution CI system?
4. How do you utilize built container images from CI (if any) from the main/production system?
5. Does your institution containerized system allows you to define automated deployments, if yes, how?
4. What are you biggest challenges or pain points when using containers, or reasons that you don't use them (fill in the blank)
5.  What do containers not do that you wish they could? What would be an ideal future?

2021-09-03 22:07 UTC, vsoch commented
@ArangoGutierrez this whole thing is going to be squashed and merged - I'm all for some projects having well organized commits but enforcing that here is overkill.

2021-09-06 07:23 UTC, kniec commented on _ideas/container-runtime-survey2021.md
> +| R4 | Do you aware of the OCI runtime spec? | single choice | yes / no |
jeezes christ

2021-09-06 07:26 UTC, kniec commented on _ideas/container-runtime-survey2021.md
> +2. Do you use CI/CD for automated build and deploy?
How about a CI/CD section in the survey?

2021-09-06 14:23 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +1. do you deal with different target architectures in your build process?
I'm with @kniec on this one - if we ask if they care about different architectures, we could probably guess the handful that are relevant. I thin asking to provide more information here won't get us much further, and it would make the survey longer and possibly lose a few folks.

2021-09-06 14:28 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +2. Do you use CI/CD for automated build and deploy?
I have mixed feelings about this, because asking about CI is out of scope for what container technology is being used, which I think was the focus of this survey. However, if this is considered relevant or important, I could see one question being added. Maybe something like:

**What do you use to build and deploy containers?**
- GitHub Workflows
- Automated builds via a registry (e.g., Docker Hub)
- On premise resources
- Circle CI
- Travis CI

I guess I'm not too keen on the above because we are basically asking about CI services. Maybe it's more appropriate to do:

**What do you use to build and deploy containers?**
- A provided CI service (GitHub Workflows, Travis CI, Circle CI, or other)
- Automated builds via a registry (e.g., Docker Hub)
- On premise resources

And then any major categories I'm missing. I'm not sure we want to (yet) be asking about rules/permissions at an org, that goes a little into privacy more than I think this survey should (e.g., to possible make it easier to identify the respondent). And the question also assumes that an org has an "institutional CI system" (most in my experience outside of national labs and industry do not). I also don't think the average user is going to know much about defining automated deployments, and @ArangoGutierrez see below - I added already the questions about pain points and ideal futures :)

2021-09-06 14:30 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +1. do you deal with different target architectures in your build process?
The question it self is bad redacted, you don't "deal" with multiple archs, your institute owns diff arch clusters, or you "want" to test your binary over diff CPU's. but users, don't "deal" with multiple CPU's during build. that is why I prefer `Do you have to build your container image for different CPU architectures?` and or `DO you care about available accelerators(GPU, FPGA, specialized network hardware) when building your container image?` , the question as it is, won't give the data reviewers any useful insightful data.

2021-09-06 14:34 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +1. do you deal with different target architectures in your build process?
Ah okay I misunderstood, - you are saying to have _two_ questions, one about architectures (very similar to what we have plus CPU) and then a _different one_ for accelerators.  You said "the question should be" so I missed that you were suggesting multiple. 

I would be fine with that.

2021-09-06 14:41 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +2. Do you use CI/CD for automated build and deploy?
My mixed feeling here is `What do you use to build and deploy containers?` in Academia and/or HPC people are not used to the `deploy containers` wording, and I wouldn't expect any HPC institution to deploy from GitHub actions. hence why  I think the questions should be done separately, a set of questions for builds and other for testing and deployment. Again, the question `What do you use to build and deploy containers?` won't provide insightful data.
If we want insightful data we need to ask about these topics by separate, or we will end up with useless data and nice graphs. 
50% use github actions.... and what? what does that tell us?
20% has on premise build and deploy.... oh awesome, what could that be.... 

We need questions that will lead to useful and decision making data, so we as a community can better direct the effort on future feature development. That is why I am advocating for very targeted questions, so then developers of Singularity/Podman/CharliCloud can sit down and say, oh users want more of X, or User are really not using Y let's not invest so many devel hours on that feature.

Or For people like Chris, knowing how people really work, and which tooling they use, can help him push ideas and features inside his org, and other could do the same for other clouds.

2021-09-06 14:45 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +2. Do you use CI/CD for automated build and deploy?
> My mixed feeling here is What do you use to build and deploy containers? in Academia and/or HPC people are not used to the deploy containers wording

Disagree - my labs / user groups at Stanford did this, and we do at the lab too.

> and I wouldn't expect any HPC institution to deploy from GitHub actions. 

Also disagree, my institution does.

> We need questions that will lead to useful and decision making data, so we as a community can better direct the effort on future feature development.

Agree partially. This first round at the survey I think should be generally. I think it would be okay to have separate questions for build and deploy, but I think most people are probably building and deploying from the same resource, so it's not so cray to group them together. I think we should start with a conservative strategy and only add _more_ questions when it's decided that is a direction the survey should go in. If we start with too many questions, period, people won't take it.

2021-09-06 14:48 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +2. Do you use CI/CD for automated build and deploy?
What does Deploy means in this discussion, do you allow GitHub Actions to deploy in production clusters? like running jobs against SLURM?  or Deploy as pushing the image to the cluster? The "deploy" word is used in diff ways in academia and cloud.

2021-09-06 14:50 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +2. Do you use CI/CD for automated build and deploy?
Most real life Prod clusters have some sort of air gap, or at least VPN or proxy protection, + running the final job with a queue manager sometimes require some perms, that is my concept of "deploy"

2021-09-06 15:09 UTC, kniec commented on _ideas/container-runtime-survey2021.md
> +| A3 | How do you rate your experience with **non-HPC containers**? | single | beginner, intermediate, expert |
I thought about that, yes. Experience with Dockerfile outside of the HPC context. How to create services... stuff like that.

2021-09-06 15:15 UTC, kniec commented on _ideas/container-runtime-survey2021.md
> +2. Do you use CI/CD for automated build and deploy?
I am on the conservative and short side here. As a first stab I reckon we learn already something even if it is 
* 20% use docker build interactively
* 30% use their own scripting to speed up repetitive tasks
* 50% use CI/CD driven by a artefact repository (if only)

2021-09-06 15:15 UTC, kniec commented on _ideas/container-runtime-survey2021.md
> +2. Do you use CI/CD for automated build and deploy?
That said, I might speak out of the desperation that we do not have any data now. :) 
I am after the basic stuff as a first go.

2021-09-06 15:42 UTC, vsoch commented
Closed / merged with #37 - thanks everyone!

2021-09-06 15:42 UTC, closed without merging

2021-09-06 16:21 UTC, ArangoGutierrez commented on _ideas/container-runtime-survey2021.md
> +2. Do you use CI/CD for automated build and deploy?
This conversation was not resolved before merging the PR @vsoch @kniec , why?

2021-09-06 16:48 UTC, vsoch commented on _ideas/container-runtime-survey2021.md
> +2. Do you use CI/CD for automated build and deploy?
It was per @kniec request in the other PR, @ArangoGutierrez why don’t you create a new issue with unresolved concerns so we can pick up the discussion. The threads here were getting unruly and I think @kniec just didn’t see them. I also think it’s important we have a rough draft merged so I can start on paperwork because these nits can go on a very long time!