Container Technologies for HPC Survey Plan (Draft)
supercontainers/containers-wg pull request #40
Opened 2021-12-04 05:16 UTC by sk8forether

The long-awaited PR is here! 🎉 

## What is this?
After some discussions (both on the [discussion page](https://github.com/supercontainers/containers-wg/discussions/39) and in [Slack](https://hpc-containers.slack.com/archives/C023C51T8SG)), and a meeting with @vsoch and @ArangoGutierrez, I put together a draft Survey Plan to add to the idea of the survey and address some remaining questions about how to conduct it.  I've added anyone I saw involved in planning/discussion as a reviewer (CC @kniec because I tried to add you as well but could not), so please feel free to add comments/questions/suggestions/answers/etc.  And I invite feedback from anyone else invested as well!

## What Changed?
* I added the file `_ideas/container-technology-survey-plan.md` which contains a draft of a survey plan including some remaining questions throughout for us to discuss and finalize.  I have (I hope helpfully) aggregated these into their own section near the bottom.
* I changed the filename `_ideas/container-runtime-survey2021.md` -> `_ideas/container-technologies-survey.md` and made some edits to the top of the file.
* The questions *have not* changed ***yet***.  My intention is to form updated questions based on the objectives - so long as they are agreeable - listed in the Survey Plan, and likely these will be shaped similarly to existing questions.  I would then like to run them by some more experience DEI folks, then commit those changes to questions so we can finalize them and submit the IRB.

## What feedback is needed/helpful?
* Please read the Survey Plan first and let me know what you think, especially about the objectives.
* If you have answers to the remaining questions - though I expect some of them may spark longer discussion - please suggest them here.
* If you think something is missing, please feel free to add it via a commit or suggest it via a comment.
* Please let me know if there are any questions in the current list that you think *should not* be changed.

Again, my goal here is to suggest a robust plan - that I welcome help improving on - that can ensure we administer the survey without introducing bias (where possible), minimize error, and to be able to leverage the data collected to present/publish helpful results to our community.  I hope this is helpful!

2021-12-04 05:52 UTC, vsoch reviewed
Bravo! Thanks for opening the PR! Here is my review, and likely others will chime in next week (it is a Friday night after all!$

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +1. Determine the makeup of the community of people using container technologies for HPC applications (and possibly all types of scientific applications?)
The population will come down to the places we send the survey, which given remote, will be across HOC, research software engineer, and researcher communities. So we don’t really get to choose a scope, but instead we can ask people to answer about their role.

I would just say “for scientific computing.”

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +2. Determine the popularity of different container technologies for HPC applications (and science apps)
Ditto.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +3. Assess the opinions about current container technologies for HPC
Ditto.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +6. Collect opinions on requested improvements to the OCI specification for HPC containers
I would just say “to OCI specifications.” Some of our suggestions may not just be scoped to HPC.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** Do we intend to focus on results pertaining to HPC?  As in, maybe we collect results from anyone who is willing to fill it out, but we are really concerned with folks using
The way I look at it is we can ask specific questions, and ways provide a “I don’t use this technology / this does not apply to me option.” I don’t think we can really artificially filter people beforehand or leave someone out because we deem them “not experienced enough for HPC” or something like that. If we advertise the survey as we’ve named it, the sample we attract will likely have people with different experiences and biases and that’s ok.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** Do we intend to focus on results pertaining to HPC?  As in, maybe we collect results from anyone who is willing to fill it out, but we are really concerned with folks using
Personally I am interested in both. I started using containers exclusively off of HPC, helped develop a container technology for it, and the non HPC experience is (in my opinion) what make the HPC container technology so successful. So I want to hear opinions from both sides.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +Convenience sampling is simplest (and thus most common for online surveys) because anyone who lands on the website can take the survey, and the survey can be widely shared unreservedly.  The major do
We don’t have the luxury of doing random sampling. So I think we should do convenience. I don’t really mind if it limits the stats.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +Convenience sampling is simplest (and thus most common for online surveys) because anyone who lands on the website can take the survey, and the survey can be widely shared unreservedly.  The major do
Random sampling could be an option in the far future if this turns into a well known survey that institutions agree to and then are able to randomly select. But not for now, that’s not going to work.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** What is our sample size?  This is determined by calculating the margin of error based on population size.  However, do we really know the population size?
I have no idea. I think we will find out.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** What is our sample size?  This is determined by calculating the margin of error based on population size.  However, do we really know the population size?
If we have a list of places we will share this it could be easy to at least estimate. Eg we can count the number of people in each slack and on each mailing list, and try to account for duplicates.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** How will we handle multiple responses (same respondent repeated input)?
We can either require an email or limit based on Ip/session (I think Google forms can do this automatically).

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +* Include optional demographics collection, especially the respondent's industry and job title
I think we could ask about job title but if we go into personal information this will not be an IRB exemption.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +* We can use the website design to implement some of the features desired in the Decreasing Error section, such as hiding questions that do not pertain
I thought we can just use Google Forms.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +* Furthermore, we should design the questions with Diversity, Equity, and Inclusion (DEI) in mind, and have the questions reviewed by folks with expertise on phrasing questions appropriately to minim
We should not be asking for personal information.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +The final survey implementation and questions can be tested by the Containers Working Group participants to ensure functionality, simplicity, and clarity.  All correctly recorded results from the tes
Yep this sounds good to me.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +> This survey is being conducted by the [Containers Working Group](https://supercontainers.github.io/containers-wg/) hosted in the [#containers-wg](https://hpc-containers.slack.com/archives/C023C51T8
Haha nice, who are you quoting there? 😊

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +* Depending on [Sampling Method](#sampling-method) chosen above, the site will either be open access (convenience sampling) or open based on some kind of access given (random sampling).
I really think we need to stick with convenience.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** Do we have a draft of an informed consent section?
That is usually part of the survey - the beginning opens with them agreeing to take it, knowing they can stop at any time, who to contact for help or concerns, etc. I’ve written these before and you can find tons of examples online.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +* Respondents will submit responses via our website form, data will be automatically stored for each response, multiple responses should be accounted for, and results will be retrieved after the surv
Google form.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** Do we plan to do any recruitment for the survey?  Will we partner with HPC/Research related marketing orgs like insideHPC, HPC wire, and related to help us expand our reach?
We could send out a feeler email to ask to promote the survey and see if anyone bites, but I don’t want to create a dependency on someone else that will ultimately make us not release any survey.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** How long to expect to keep the survey open for?  We will need to keep the survey open long enough to reach the appropriate sample size that meets the desired margin of error
This will depend on when it goes out I think, and we don’t have to decide now. I could see announcing and promoting at a conference or event and on social media and slacks, and then doing a refresh promotion once a week, and maybe open for 3-4 weeks to give people a chance to respond.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +## Remaining Questions
I would delete this repeated section it’s confusing to have it twice.

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey.md
> +This survey is being conducted by the [Containers Working Group](https://supercontainers.github.io/containers-wg/) with the goal of assessing the community's opinion about container technologies for
for scientific computing

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey.md
> +### Informed Consent
This also needs to provide a contact if they have questions or concerns, and stress that their participation is voluntary. If you do a Google Search there are good examples!

2021-12-04 05:52 UTC, vsoch commented on _ideas/container-technologies-survey.md
> +plan: https://github.com/sk8forether/containers-wg/blob/main/_ideas/container-technology-survey-plan.md
If you have this as front end matter, it’s not known to the template so maybe you want to link to it somewhere? And sorry if I missed it!

2021-12-06 08:57 UTC, kniec commented on _ideas/container-technologies-survey-plan.md
> +6. Collect opinions on requested improvements to the OCI specification for HPC containers
I like 5 as it takes the temperature. how about asking about which specification needs an HPC update (image or runtime).
6 as a free comment field for people to put in what actually needs changing?

2021-12-06 08:57 UTC, kniec commented on _ideas/container-technologies-survey-plan.md
> +* and possibly others
Do we want to call out ML/DL workloads explicitly? Even though some might not see them as HPC they face (or will face) the same problems (devices, shared filesystems, MPI)?

2021-12-06 08:57 UTC, kniec commented on _ideas/container-technologies-survey-plan.md
> +| 2. Determine the popularity of different container technologies for HPC applications (and science apps) | Nominal | list of container technologies and locations container technologies are used (see
I'd say container runtime - not technology.

2021-12-06 08:57 UTC, kniec commented on _ideas/container-technologies-survey-plan.md
> +| 3. Assess the opinions about current container technologies for HPC | Ordinal | level of experience with HPC, level of experience with specific container technologies used, level of satisfaction wi
technology -> runtime

2021-12-06 08:57 UTC, kniec commented on _ideas/container-technologies-survey-plan.md
> +
I'd like to include the whole stack. 
- runtime (already covered)
- build: how do users build their images 
   - what artefect (Dockerfile, SIF recipe)
   - where (CI/CD, local machine)
   - how (using docker build, buildah, singularity build)
- distribute:
  - which registry is used
  - CVMFS (like biocontainers)

2021-12-06 08:57 UTC, kniec commented on _ideas/container-technologies-survey-plan.md
> +* Container registries
* Container builds

2021-12-06 08:57 UTC, kniec commented on _ideas/container-technologies-survey-plan.md
> +* We can use the website design to implement some of the features desired in the Decreasing Error section, such as hiding questions that do not pertain
Google form with authentication? me dislike... :)

2021-12-06 08:57 UTC, kniec commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** Do we plan to do any recruitment for the survey?  Will we partner with HPC/Research related marketing orgs like insideHPC, HPC wire, and related to help us expand our reach?
The container-wg participants should have ways of amplifying this (I am pretty sure I do internally).

2021-12-06 23:12 UTC, reidpr reviewed
Thanks for your hard work, Peter. Several suggestions in-line.

2021-12-06 23:12 UTC, reidpr commented on _ideas/container-technologies-survey-plan.md
> +* Furthermore, we should design the questions with Diversity, Equity, and Inclusion (DEI) in mind, and have the questions reviewed by folks with expertise on phrasing questions appropriately to minim
I agree this review is important. Re. "personal information", we should be more specific. Demographics is one thing; personally identifiable information is another. IIRC the IRB regulations and related privacy rules have vocabulary we can use if needed (I'm not sure we do need it).

2021-12-06 23:12 UTC, reidpr commented on _ideas/container-technologies-survey-plan.md
> +The final survey implementation and questions can be tested by the Containers Working Group participants to ensure functionality, simplicity, and clarity.  All correctly recorded results from the tes
IMO it would be better to test on people uninvolved, but perhaps close enough to team members that their responses would be a COI. I hesitate to include pilot results with the final, given that hopefully we'll change the survey based on what we learn in the pilot(s).

2021-12-06 23:12 UTC, reidpr commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** Do we have a draft of an informed consent section?
IRB will need the text of the informed consent in their submission packet.

2021-12-06 23:12 UTC, reidpr commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** Do we plan to do any recruitment for the survey?  Will we partner with HPC/Research related marketing orgs like insideHPC, HPC wire, and related to help us expand our reach?
https://en.wikipedia.org/wiki/Vuvuzela

2021-12-06 23:12 UTC, reidpr commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** How long to expect to keep the survey open for?  We will need to keep the survey open long enough to reach the appropriate sample size that meets the desired margin of error
IMO it would be good to set some targets for responses: total number, number from each key recruiting dimension, possibly demographics, etc.

2021-12-07 19:58 UTC, ArangoGutierrez requested changes
mostly agree with V, please review and correct as requested

2021-12-07 19:58 UTC, ArangoGutierrez commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** Do we intend to focus on results pertaining to HPC?  As in, maybe we collect results from anyone who is willing to fill it out, but we are really concerned with folks using
Agree, we are interested in anyone trying to use containers for science, so I would remove this `remaining question`

2021-12-07 19:58 UTC, ArangoGutierrez commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** Are we planning to use convenience sampling or a form of random sampling?
Agree, let's do our best effort, but not to stop or defer this survey for this. Containers in science is a growing topic, so getting to know who is using it is also a good part of the result

2021-12-07 19:58 UTC, ArangoGutierrez commented on _ideas/container-technologies-survey-plan.md
> +Convenience sampling is simplest (and thus most common for online surveys) because anyone who lands on the website can take the survey, and the survey can be widely shared unreservedly.  The major do
++

2021-12-07 19:58 UTC, ArangoGutierrez commented on _ideas/container-technologies-survey-plan.md
> +If we were to select a random sampling method, we could implement it by specifically selecting a wide range of institutions, companies, and/or platforms and randomly select participants to get a samp
Agree, let's not over engineer this

2021-12-07 19:58 UTC, ArangoGutierrez commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** What is our sample size?  This is determined by calculating the margin of error based on population size.  However, do we really know the population size?
part of the question to is the the not the sampling size, but the survey size, so is not a question, is an outcome. Agree with V and Reid

2021-12-07 19:58 UTC, ArangoGutierrez commented on _ideas/container-technologies-survey-plan.md
> +* Container registries
Add `container builds`

2021-12-10 23:55 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +Purpose of survey: To assess the community's opinion about container technologies for HPC specifically, and scientific computing generally.
I think we will also want to present our findings about the community's opinion in places where it might be helpful for others to make decisions too about where to focus effort.

2021-12-11 01:26 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +6. Collect opinions on requested improvements to the OCI specification for HPC containers
@ArangoGutierrez I typically think of "HPC containers" as short-hand for "containers with HPC applications in them", but yes, agree with @vsoch about the scope of the questions.

@kniec Yes, I think your idea is partly captured in the table below for data to collect for Optional Objectives, but I have also made a note for when I update the list of questions.

2021-12-11 01:29 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +Our **target population** is all people developing, maintaining, or in any way using container technologies for HPC and/or scientific applications in
I agree with both of you.  I think we will have to phrase the questions carefully, and break out results if possible, but ultimately expect some bias in results.

2021-12-11 01:54 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** What is our sample size?  This is determined by calculating the margin of error based on population size.  However, do we really know the population size?
Yeah, I agree @vsoch.  I think we do need the initial survey to use convenience sampling to help us even take a stab at answering our potential population size.  However, we should decide on a minimum sample size in order to take a stab at seeing if it is representative (AKA "we have enough responses that we have a chance of accounting for bias in the results"), and also to determine how long our window will be for accepting responses.
 
 @reidpr Yes, that is a good point.  I suppose we can admit safely to not knowing the population size (and thus not calculate the margin of error) because nobody does.  The CI should be sufficient.
 
 @ArangoGutierrez The sample size is only an outcome for convenience sampling (random sampling would require deciding beforehand), and even still we have control over the minimum and maximum cutoffs (see my note to V), which determines our window for keeping the survey open.  It sounds like we are going with convenience sampling, so we should at least decide on a minimum number of results to consider the survey response set "complete".

2021-12-11 02:02 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** What is our sample size?  This is determined by calculating the margin of error based on population size.  However, do we really know the population size?
I think for now it's fine to define the method, and not need to provide an exact number. E.g.,:

 - identify communities we will send survey to
 - get number of people in general (a good estimate, since most people are by default in general)
 - add up, but subtract a conservative estimate of overlap
 - some percentage (10%)? of that is a good sample size to shoot for

2021-12-11 02:11 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +* We should aim for a confidence level of 95% and calculate our margin of error to determing appropriate sample size
Hm.  I originally wrote this when still considering random sampling methods.  @reidpr Do you have a suggestion for how we should phrase how we are going to capture/express the sampling error here?  Or is this already covered by the aforementioned 1-2 sentences we will include about using convenience sampling?

2021-12-11 02:11 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +* We should aim for a confidence level of 95% and calculate our margin of error to determing appropriate sample size
(Removing this line in the plan for now, and will add more in it's place if you have suggestions)

2021-12-11 02:18 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +| 2. Determine the popularity of different container technologies for HPC applications (and science apps) | Nominal | list of container technologies and locations container technologies are used (see
In the meeting with @vsoch and @ArangoGutierrez, we decided on "container technologies" to expand on runtimes, as well as to include other tools that may be related but are not container runtimes or implementations, such as orchestration tools like Kubernetes.

2021-12-11 02:20 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +| 3. Assess the opinions about current container technologies for HPC | Ordinal | level of experience with HPC, level of experience with specific container technologies used, level of satisfaction wi
See my response above.

2021-12-11 02:30 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +| 2. Determine the popularity of different container technologies for HPC applications (and science apps) | Nominal | list of container technologies and locations container technologies are used (see
I think it tells us (to varying degrees):
* Answers to a lot that we do not currently know (i.e. what technologies are people using in their day-to-day within our community, do people actually use Kubernetes for HPC [sidenote: the answer is yes, but how many people are doing this?])
* If our preferred tools as a WG are representative of the population (thus affecting the types of tools and solutions we may be inclined to create, but may or may not be what the community desires), and
* The beginning of a framework for considering which features of the OCI spec people are interacting with right now

I don't think we will get a representative sample that we can definitively say "people prefer X technology over Y", and I wouldn't dare try to say that from a convenience sample, but I think we can say "technology X is being used by this percentage of our sample, meaning it is likely or not likely a common tool for our community".  Plus, if people say negative things about a technology, but admit to never having used it, that could be helpful for weeding out the nonsense.

Do you think we should not collect this information, @reidpr?

2021-12-11 02:58 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** How will we handle multiple responses (same respondent repeated input)?
I like the idea of using Google forms, and it does have a feature for this with some customization options.  I've used it and find it to be relatively intuitive as both the designer and respondent.  I don't know if it will allow us to present questions based on previous answers (i.e. if someone says "no" to "Do you use X technology?" then we don't want to ask them more questions about it).  I suppose we can also plan to evaluate and decide on a survey tool later.

2021-12-11 03:07 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +* Include optional demographics collection, especially the respondent's industry and job title
Yes, I agree with @reidpr that we should collect demographics (part of why I think it would be good to have experienced DEI folks take a look at our questions as a double-check to make sure they look inclusive and follow best practices) so that we can report on the diversity of our sample size.  It would not be ideal to base all of our results on the opinions of one demographic, for example, and not know that this was a clear bias in our dataset because we didn't ask.

I think we can still potentially get the exemption, but even if we do not then I agree it is worth still moving forward with demographic collection.

As a side-note, I recall reading a study that demonstrated a bias in results that hurt marginalized groups when demographics were collected at the front of surveys, so I think we should collect it at the end to potentially avoid this, and reinforce that it is optional.

2021-12-11 03:18 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +The final survey implementation and questions can be tested by the Containers Working Group participants to ensure functionality, simplicity, and clarity.  All correctly recorded results from the tes
Hm.  I'm not sure I can imagine who would be able to pilot the survey for us if we do not do it within our group...  Who would you suggest we ask to respond to the pilot?  And do you expect that we will need to update the IRB if we change questions after the pilot?

2021-12-11 03:20 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +> This survey is being conducted by the [Containers Working Group](https://supercontainers.github.io/containers-wg/) hosted in the [#containers-wg](https://hpc-containers.slack.com/archives/C023C51T8
Oh, um, myself I guess 😆   I think I also looked at @kniec's original intro and some of your responses in slack, so maybe more accurately I am quoting the 3 of us in bits.

2021-12-11 03:22 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +| 1. Determine the makeup of the community of people using container technologies for HPC applications | Nominal | demographic categories, industry, job title (or student status) |
This means we won’t be able to do an IRB exemption. If this is the case I may not want to be the one with their name on the line for filing an IRB.

2021-12-11 03:28 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** Do we have a draft of an informed consent section?
@vsoch Would you be comfortable adding the informed consent paragraph in the `_ideas/container-technologies-survey.md` file since you have written them before?  You should have write access to commit to this repo/PR.  I am happy to be a contact for help/concerns if that helps, and can take a stab at it if you can't get to it.

2021-12-11 03:35 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +* and possibly others
I added Data Scientists as I think it would cover ML/DL/Big Data if the other categories do not.  I think in general ML/DL fall under scientific computing, so earlier suggested changes should help to include those folks.

2021-12-11 03:35 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** Do we intend to focus on results pertaining to HPC?  As in, maybe we collect results from anyone who is willing to fill it out, but we are really concerned with folks using
Agreed and removed.  Thanks, both of your comments like up with what I was thinking was our goal, but wanted double-checked.  The only concern I see is that containers for HPC vs. other application types do have different requirements/challenges, but as @reidpr said in an earlier comment, we can break those out as separate in the results.

2021-12-11 03:36 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +| 1. Determine the makeup of the community of people using container technologies for HPC applications | Nominal | demographic categories, industry, job title (or student status) |
Agreed.  It's what I intended, though I see now how that was not what it says, so I clarified that in the text more explicitly.  Thanks.

2021-12-11 03:36 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +
Yes, that is the intention, and thank you for the clear list!  I have added the missing parts of this in the list below in the "Focus of Questions" section.

2021-12-11 03:36 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +* We can use the website design to implement some of the features desired in the Decreasing Error section, such as hiding questions that do not pertain
I think this is a good idea to explore which survey tool/site to use after we are happy with the plan and questions themselves.  I apologize for phrasing here, I didn't mean to imply we would be building a survey tool, just that the design would accommodate hiding questions that don't pertain.  Fixed the phrasing.

2021-12-11 03:36 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +* Respondents will submit responses via our website form, data will be automatically stored for each response, multiple responses should be accounted for, and results will be retrieved after the surv
Changed to "survey tool (TBD)" since it looks like it is being discussed above.

2021-12-11 03:38 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** Do we plan to do any recruitment for the survey?  Will we partner with HPC/Research related marketing orgs like insideHPC, HPC wire, and related to help us expand our reach?
I have plans set up to send it out to the XSEDE community, which should reach the inbox of a number of HPC folks in the U.S.

2021-12-11 03:41 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** Do we plan to do any recruitment for the survey?  Will we partner with HPC/Research related marketing orgs like insideHPC, HPC wire, and related to help us expand our reach?
Has anyone reached out to HPCwire or inside HPC?  If not, I could talk to the PR person for my Center at Cornell about it since he gets articles in HPCwire and such about the work we do.

2021-12-11 03:43 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** How long to expect to keep the survey open for?  We will need to keep the survey open long enough to reach the appropriate sample size that meets the desired margin of error
Yes, I agree with @reidpr.  We should have some idea of at least a minimum number of respondents.

2021-12-11 03:51 UTC, sk8forether commented on _ideas/container-technologies-survey.md
> +plan: https://github.com/sk8forether/containers-wg/blob/main/_ideas/container-technology-survey-plan.md
No, you didn't miss it, and I don't have it as front end matter...  I just added it to the yaml like a fool thinking it would just get it's own box.  It worked in the Markdown, but I don't know how to see what it will look like on the page.  If you have a better way to include the link to the plan at the top, please feel free to commit it (you should have push access to this repo/PR) or suggest it to me here.

2021-12-11 03:53 UTC, sk8forether commented on _ideas/container-technologies-survey.md
> +### Informed Consent
Would you be willing to add a draft here since you have experience (you should have access to push to this repo/PR)?  If not, then I will take a stab at it.

2021-12-11 03:56 UTC, vsoch commented on _ideas/container-technologies-survey.md
> +### Informed Consent
Sure! But let’s do as another PR after this one is finished.

2021-12-11 03:57 UTC, vsoch commented on _ideas/container-technologies-survey.md
> +plan: https://github.com/sk8forether/containers-wg/blob/main/_ideas/container-technology-survey-plan.md
You can just refer to it as a link in the content would be my suggestion - no need to even include it up here.

2021-12-11 04:01 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +* Furthermore, we should design the questions with Diversity, Equity, and Inclusion (DEI) in mind, and have the questions reviewed by folks with expertise on phrasing questions appropriately to minim
I think we should ask for basic demographic information such as gender, ethnicity, etc. so that we can be sure we are not simply getting results from 1 demographic and basing our results on that without knowing it (which would be unintentionally ignoring the voices of all the other demographics).  I do not think we should collect any personally identifiable information.

2021-12-11 04:15 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +* Respondents will submit responses via a survey tool (TBD) form, data will be automatically stored for each response, multiple responses should be accounted for, and results will be retrieved after
Based on some of the comments, I changed this to "survey tool (TBD)", but I the comments have disappeared.  What I recall is that there was some votes for Google form, some for Survey Monkey, and I apologize that I made it sound like I was suggesting a custom website implementation (just poor wording choice on my part).  What tool we use could be determined after this PR is complete, but leaving this comment here for the sake of discussion if needed.

2021-12-11 04:20 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** How long do we expect to keep the survey open for?  As in, what is our minimum sample size (and then we wait until we get this before considering closing the survey)?
Comments on this somehow got washed away when I made commits, but there was some discussion in a couple places about this.  There was a comment from @reidpr about target sample size and potentially target sizes to collect from demographics, I think?  I believe we need at least a minimum sample size to hit rather than a time window, at least.

2021-12-11 04:26 UTC, vsoch commented on _ideas/container-technologies-survey-plan.md
> +* Respondents will submit responses via a survey tool (TBD) form, data will be automatically stored for each response, multiple responses should be accounted for, and results will be retrieved after
When threads get large the comments still exist, but you have to scroll down carefully until you see the little expand menu. It looks like this:

![image](https://user-images.githubusercontent.com/814322/145663658-ddc5a16a-f76d-4bb6-a5e3-11ca58938e09.png)

GitHub hides them when the thread gets too long, a feature I'm not a fan of.

2021-12-11 04:26 UTC, sk8forether commented
Ok, I think I have made all the edits that I can for now, and resolved suggestions that are finished.  There are several ongoing conversations in comments, but I think only one of them is a blocker for this PR:
* [Should we include demographics questions?](https://github.com/supercontainers/containers-wg/pull/40/files#r762389558)

Non-blocking suggestions/conversations that remain open that could be answered/discussed afterwards:
* [What survey tool should we use?](https://github.com/supercontainers/containers-wg/pull/40/files#r767086375)
* [Who should be in the pilot test group?](https://github.com/supercontainers/containers-wg/pull/40/files#r763474418)
* [Where should we recruit?](https://github.com/supercontainers/containers-wg/pull/40/files#r762389831)
* [What is our minimum sample size to target before closing the survey?  (Or should we use some other metric?)](https://github.com/supercontainers/containers-wg/pull/40/files#r767086840)

I would suggest moving the conversations for the non-blocking questions to either the Discussions page or to Slack for now.  Does this work?

As for the blocking question, I think we should have a resolution to this before finalizing the questions.  I believe I can begin making edits to the questions now to add to this PR, but please let me know if you see anything else that needs attention.

2021-12-11 04:33 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +* Respondents will submit responses via a survey tool (TBD) form, data will be automatically stored for each response, multiple responses should be accounted for, and results will be retrieved after
Oh, they are completely hidden in the "Changed Files" view, which is where I was working through the comments...

2021-12-11 04:35 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +* Respondents will submit responses via a survey tool (TBD) form, data will be automatically stored for each response, multiple responses should be accounted for, and results will be retrieved after
I see now that in the "Jump to Conversation" menu, there are several marked "Outdated".  I think those might be the ones that got lost.

2021-12-11 04:41 UTC, sk8forether commented on _ideas/container-technologies-survey-plan.md
> +***Remaining Question:*** How long do we expect to keep the survey open for?  As in, what is our minimum sample size (and then we wait until we get this before considering closing the survey)?
Fishing through the "Outdated" conversations, I found a more recent suggestion from @vsoch:

> I think for now it's fine to define the method, and not need to provide an exact number. E.g.,:
> 
> * identify communities we will send survey to
> * for slack, get number of people in the "general" channel (a good estimate, since most people are by default in general). For mailing list, get a count (hopefully we can ask if we don't have access)
> * add up, but subtract a conservative estimate of overlap
> * some percentage (10%)? of that is a good sample size to shoot for

2021-12-11 04:45 UTC, vsoch commented
> Should we include demographics questions?

@sk8forether I think the answer to demographics is yes, albeit it means that someone else can take the lead on the IRB - I don't want to be the person in charge of others' personal information! I agree it seems important.

> What survey tool should we use?

It sounds like there is issue with google forms, so something like SurveyMonkey works for me.

> Who should be in the pilot test group?

It's us :)

> Where should we recruit?

For the pilot, it's us (we don't need to recruit) for the actual study, it will be our various slacks, mailing lists, and work lists.

> What is our minimum sample size to target before closing the survey? (Or should we use some other metric?)

I think I outlined a method for this, which is all we need for now until we have a list of our groups / numbers in each.

2021-12-13 17:24 UTC, reidpr commented on _ideas/container-technologies-survey-plan.md
> +* We should aim for a confidence level of 95% and calculate our margin of error to determing appropriate sample size
I would just put something along the lines of what I wrote above, but better written. Maybe a statistics person would have something better.

2021-12-13 17:25 UTC, reidpr commented on _ideas/container-technologies-survey-plan.md
> +| 1. Determine the makeup of the community of people using container technologies for HPC applications | Nominal | demographic categories, industry, job title (or student status) |
Why it is important to have an IRB exemption instead of expedited review? (We're not getting into full review territory IMO.)

2022-02-23 20:07 UTC, merged